# Site settings
title: Madhur Kapoor
email: madhur2511@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://madhur2511.github.io" # the base hostname & protocol for your site
github_username:  madhur2511
linkedin_username: madhur2511

# Build settings
markdown: kramdown
